version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
