version: '3'
services:
  postgres:
    build: ./postgresql
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql_script.sh:/docker-entrypoint-initdb.d/script.sh