version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_ct
    # ports:
    #   - '5432:5432'
    networks:
      - 'ft_transcendence'
    volumes:
      - pg-data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend_ct
    ports:
      - '3000:3000'
    networks:
      - 'ft_transcendence'
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    container_name: frontend_ct
    ports:
      - '3001:3001'
    networks:
      - 'ft_transcendence'
    depends_on:
      - backend

volumes:
  pg-data:

networks:
  ft_transcendence:
    driver: bridge
    name: ft_transcendence
